---
title: "Maybe I Won't Die Alone"
date: 2018-06-26
---

title: Maybe I Won't Die Alone
author: AgentShir
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Dating. Why did I want to do this again?

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
